export const podcasts = [
  {
    id: 'pod-1',
    emoji: '🎙️',
    name: 'Psychedelic Stories',
    episode: null,
    type: 'Podcast',
    detail: 'Origin story — Tehran, asylum, 5-MeO-DMT, and the birth of Safar',
    url: 'https://music.amazon.com/podcasts/b6e1a2ab-c983-45e1-af04-950ae749aba4/psychedelic-stories',
    description: "Sabba shares the full origin story — born in Tehran during the Iran-Iraq War, his family's flight through Greece to the U.S., his 20-year tech career, and the 5-MeO-DMT experience that shattered everything and rebuilt it. This is the foundational episode.",
  },
  {
    id: 'pod-2',
    emoji: '🎧',
    name: 'Entrepreneurs in Recovery',
    episode: 'Ep. 061',
    type: 'Podcast',
    detail: 'AI, psychedelics & accessibility in mental health',
    url: 'https://open.spotify.com/episode/1fgldyJ0rUUYQujGKzLuqD',
    description: 'Host Jesse Harless and Sabba go deep on the intersection of AI and psychedelics, the broken therapeutic model, systemic barriers to mental health care, and why integration — not the medicine — is where real change happens.',
  },
  {
    id: 'pod-3',
    emoji: '🌿',
    name: 'Leadershipedelics',
    episode: 'S3 Ep. 8',
    type: 'Podcast',
    detail: 'Conscious leadership, fatherhood & psychedelic business',
    url: 'https://www.leadershipedelics.com/1860291/episodes/12715722-sabba-nazhand-conscious-leadership-fatherhood-psychedelic-business-and-personal-growth',
    description: 'A conversation about overcoming burnout, the transformative power of psychedelics, and how vulnerability and emotional openness are superpowers for fathers and leaders.',
  },
  {
    id: 'pod-4',
    emoji: '🌐',
    name: 'Webdelics',
    episode: null,
    type: 'Podcast',
    detail: 'Embracing emotions & masculinity — transformational journey with psychedelics',
    url: 'https://rephonic.com/podcasts/webdelics-podcast',
    description: 'Sabba explores masculinity, emotional expression, and how psychedelics helped him reconnect with parts of himself that survival mode had buried.',
  },
  {
    id: 'pod-5',
    emoji: '🏃',
    name: 'Mile 40 Podcast',
    episode: 'Ep. 126',
    type: 'Podcast',
    detail: 'Integration, innovation & moving with intention',
    url: 'https://creators.spotify.com/pod/profile/bishoy-tadros/episodes/Ep-126---Integration--Innovation---Moving-With-Intention-Featuring-Sabba-Nazhand-e31854c',
    description: 'Host Bishoy Tadros and Sabba discuss the immigrant experience, psychedelic therapy, mission-driven entrepreneurship, and the path to authenticity and conscious leadership.',
  },
  {
    id: 'pod-6',
    emoji: '🐝',
    name: 'Bridges Between Us',
    episode: null,
    type: 'Podcast',
    detail: 'Conscious sales, burnout recovery & the future of work',
    url: 'https://podcasts.apple.com/mu/podcast/conscious-at-work-w-sabba-nazhand/id1594188937?i=1000646049216',
    description: "A conversation on the future of work, the state of modern sales teams, burnout, and how Conscious Leadership principles transformed Sabba's approach to selling and leading.",
  },
  {
    id: 'pod-7',
    emoji: '🪷',
    name: 'The TripSitting Podcast',
    episode: 'Ep. 070',
    type: 'Podcast',
    detail: 'Coming back to ourselves — fleeing Iran & healing through psychedelics',
    url: 'https://open.spotify.com/episode/1lmR7k9yMydDhFYvjRb4Un',
    description: 'Sabba tells his story of fleeing Iran as a newborn, arriving in the U.S. five years later, and how psychedelics helped him come back to himself.',
  },
  {
    id: 'pod-8',
    emoji: '🔬',
    name: 'TrueLife',
    episode: null,
    type: 'Podcast',
    detail: 'Psychedelic Science Exodus — Safar, integration & the future of the field',
    url: 'https://podscan.fm/podcasts/truelife/episodes/sabba-nazhand-amp-jack-gorsline-psychedelic-science-exodous',
    description: 'Recorded at Psychedelic Science 2025 — Sabba and Jack Gorsline discuss Safar, AI-driven integration, and the future of the psychedelic ecosystem.',
  },
  {
    id: 'pod-9',
    emoji: '✊',
    name: 'Minority Trip Report™',
    episode: 'Co-Creator',
    type: 'Podcast',
    detail: 'Spotlighting underrepresented voices in psychedelics & consciousness',
    url: 'https://www.minoritytrip.com',
    description: 'Sabba co-created this platform to spotlight underrepresented perspectives in mental health, psychedelics, and consciousness — using psychedelics as a lens to explore identity and transformation.',
  },
  {
    id: 'pod-10',
    emoji: '📈',
    name: 'Startup Sales',
    episode: 'Ep. 059',
    type: 'Podcast',
    detail: 'Building top-performing enterprise sales teams (WorkGenius era)',
    url: 'https://www.podchaser.com/podcasts/startup-sales-686446/episodes/interview-for-top-sales-with-s-45755565',
    description: "From Sabba's tech leadership era — a deep dive into building and scaling enterprise sales teams, recorded while VP of Sales at WorkGenius.",
  },
  {
    id: 'pod-11',
    emoji: '👗',
    name: 'Fashion Is Your Business',
    episode: null,
    type: 'Podcast',
    detail: 'Recorded live at eTail East, Boston — AI workforce solutions',
    url: 'https://podcasts.apple.com/gb/podcast/sabba-nazhand-workgenius-julian-kahlon-project-verte/id954158712?i=1000452731102',
    description: 'Recorded on location at eTail East in Boston — Sabba discusses WorkGenius and the AI-powered marketplace for enterprise freelancer engagement.',
  },
  {
    id: 'pod-12',
    emoji: '🧊',
    name: 'WELLPOWER: Breath, Cold, & Biohacking Podcast',
    episode: null,
    type: 'Coming Soon',
    detail: 'Episode coming soon',
    url: 'https://open.spotify.com/show/7EKXTOqgKIXe6kmlwkJvts',
    description: 'Upcoming episode — stay tuned.',
  },
  {
    id: 'pod-13',
    emoji: '🍄',
    name: 'The Psychedelic Scene Podcast',
    episode: null,
    type: 'Coming Soon',
    detail: 'Episode coming soon',
    url: 'https://open.spotify.com/show/10xHqbyEmuubsGLBHPwAwx',
    description: 'Upcoming episode — stay tuned.',
  },
]

export const articles = [
  {
    id: 'art-1',
    emoji: '📝',
    name: 'Reality Sandwich',
    episode: null,
    type: 'Article',
    detail: 'The Hive and the Seeker: Psychedelics, Integration, and the Composition of Connection',
    url: 'https://realitysandwich.com/psychedelics-integration-connection/',
    description: 'An essay on integration as resistance — how the hive metaphor mirrors the psychedelic journey, and why carrying insights into daily life is the real work. "Integration is the quiet rebellion of remembrance."',
  },
  {
    id: 'art-2',
    emoji: '🧬',
    name: 'Psychedelic Scene Magazine',
    episode: null,
    type: 'Article',
    detail: "On Generational Trauma: You're Not Broken — You're Running Someone Else's Code",
    url: 'https://psychedelicscene.com/2026/04/07/generational-trauma/',
    description: "Sabba's essay on inherited survival programming — from revolutionary Iran to American suburbia — and how psychedelics dissolve the narration long enough to meet yourself before the download. Published April 2026.",
  },
]

export const press = [
  {
    id: 'press-1',
    emoji: '📰',
    name: 'Tricycle Day',
    episode: 'Featured Interview',
    type: 'Press',
    detail: 'AI in psychedelic healing, indigenous wisdom in tech (80K+ subscribers)',
    url: 'https://www.tricycleday.com/p/sabba-nazhand',
    description: "The flagship interview — Tricycle Day's 80K+ subscriber newsletter featured Sabba on what's broken about current integration models, bringing indigenous wisdom into a tech product, and why AI belongs in psychedelic healing.",
  },
  {
    id: 'press-2',
    emoji: '📡',
    name: 'Send2Press / National Newswire',
    episode: 'Launch Coverage',
    type: 'Press',
    detail: 'Safar launch syndicated across 15+ outlets',
    url: 'https://www.send2press.com/wire/integration-enterprises-pbc-dba-safar-launches-the-first-operating-system-for-human-transformation/',
    description: 'The official Safar launch press release — syndicated across Fox21, Florida Newswire, Massachusetts Newswire, and 15+ other outlets. Announced the first Operating System for Human Transformation, powered by Salience Intelligence™.',
  },
  {
    id: 'press-3',
    emoji: '🏆',
    name: 'Webdelics Top 100',
    episode: 'Thought Leader Recognition',
    type: 'Press',
    detail: 'Named among top thought leaders in psychedelic space',
    url: 'https://www.webdelics.com/top-lists/thought-leaders-content-creators',
    description: 'Recognized as an emerging thought leader in conscious leadership and psychedelic integration among the top 100 thought leaders and content creators in the psychedelic space.',
  },
]

export const speaking = [
  {
    id: 'speak-1',
    emoji: '🎤',
    name: 'Awakening 2025',
    episode: 'Keynote & Panelist',
    type: 'Keynote',
    detail: 'Keynote + Psychedelics & Technology panel — Psychedelic Institute of LA',
    url: 'https://www.liiightspace.com/post/psychedelics-technology-panel',
    description: 'Delivered a keynote and joined the Psychedelics & Technology panel alongside Aaron Chi, Dr. Sanjay Manchanda, and Dru Ali at Awakening 2025, hosted by the Psychedelic Institute of Los Angeles.',
  },
  {
    id: 'speak-2',
    emoji: '🌍',
    name: 'The Psychedelic Assembly',
    episode: null,
    type: 'Speaker',
    detail: 'From War-torn Iran to Conscious Leadership',
    url: 'https://www.thepsychedelicassembly.com/',
    description: "Sabba's keynote on the journey from asylum seeker to tech executive to conscious leader — and how psychedelics catalyzed the transformation.",
  },
  {
    id: 'speak-3',
    emoji: '🌏',
    name: 'Global Psychedelic Week',
    episode: null,
    type: 'Speaker',
    detail: 'Psychedelics & AI: Consciousness, Technology, and the Future',
    url: 'https://www.globalpsychedelicweek.com/speakers',
    description: 'A talk on the convergence of psychedelics and artificial intelligence — how technology can serve consciousness rather than extract from it.',
  },
  {
    id: 'speak-4',
    emoji: '🐝',
    name: 'In The Beehive',
    episode: null,
    type: 'Panel',
    detail: 'Emerge and See: Psychedelics and the Future',
    url: 'https://inthebeehive.com/panels',
    description: 'Panel discussion on the emerging psychedelic landscape and what the future holds for practitioners, patients, and the broader ecosystem.',
  },
  {
    id: 'speak-5',
    emoji: '🌲',
    name: 'Hollyhock — Canadian Psychedelic Summit 2023',
    episode: null,
    type: 'Speaker',
    detail: 'Presenter at Cortes Island retreat centre',
    url: 'https://hollyhock.ca/people/sabba-nazhand/',
    description: "Presented at the Canadian Psychedelic Summit at Hollyhock's legendary retreat centre on Cortes Island, British Columbia.",
  },
  {
    id: 'speak-6',
    emoji: '✨',
    name: 'Sensoria Presents',
    episode: null,
    type: 'Speaker',
    detail: 'Fundraiser for the Shulgin Farm',
    url: 'https://sensoria.rsvpify.com/',
    description: 'Speaker at the Sensoria fundraiser benefiting the Shulgin Farm — honoring the legacy of Sasha and Ann Shulgin.',
  },
  {
    id: 'speak-7',
    emoji: '🎥',
    name: 'AMA — Why Business Leaders Are Turning to Psychedelics',
    episode: null,
    type: 'Video',
    detail: 'Video — YouTube',
    url: 'https://www.youtube.com/watch?v=TXjCePHehbM',
    description: 'An open AMA exploring why executives, founders, and business leaders are increasingly turning to psychedelic experiences for clarity, creativity, and conscious leadership.',
  },
  {
    id: 'speak-8',
    emoji: '🎓',
    name: 'George Washington University',
    episode: 'Guest Lecturer',
    type: 'Lecture',
    detail: 'School of Business — Event Management & Hospitality programs',
    url: null,
    description: "Guest lecturer at GWU's School of Business, delivering presentations for the event management and hospitality disciplines.",
  },
]

export const speakingTopics = [
  { label: 'The Integration Gap — Why Insight Without Structure Fades', color: '#c4613a' },
  { label: 'Ethics of Building in Sacred & Healing Spaces', color: '#b8943e' },
  { label: 'AI Meets the Soul — Technology for Human Transformation', color: '#6b8c5e' },
  { label: 'Intergenerational Trauma & the Immigrant Founder Story', color: '#6a9ec8' },
  { label: 'Conscious Sales Leadership & Vulnerability at Work', color: '#a89e90' },
  { label: 'Measurement as Medicine — Making the Invisible Visible', color: '#c4613a' },
]

export const footerTags = [
  'Psychedelics',
  'AI + Healing',
  'Conscious Leadership',
  'Integration',
  'Founder Story',
]
